apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: example-selfsigned
spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: example-com-selfsigned
spec:
  secretName: example-com-selfsigned
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - example.com
  - '*.example.com'
